name: Send Discord Webhook

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        uses: actions/github-script@v6
        with:
          script: |
            const webhookUrl = process.env.WEBHOOK_URL;
            const pullRequest = context.payload.pull_request;
            
            const message = {
              content: 'A Pull Request has been created or updated!',
              embeds: [
                {
                  title: pullRequest.title,
                  url: pullRequest.html_url,
                  description: pullRequest.body,
                  color: 5814783
                }
              ]
            };

            await fetch(webhookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(message)
            });
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
